//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPapeConsola.ServicioLaPape {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLaPape.ILaPape")]
    public interface ILaPape {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/InsertarProducto", ReplyAction="http://tempuri.org/IProducto/InsertarProductoResponse")]
        Entidades.Producto InsertarProducto(Entidades.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/InsertarProducto", ReplyAction="http://tempuri.org/IProducto/InsertarProductoResponse")]
        System.Threading.Tasks.Task<Entidades.Producto> InsertarProductoAsync(Entidades.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/ListarProducto", ReplyAction="http://tempuri.org/IProducto/ListarProductoResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Producto> ListarProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/ListarProducto", ReplyAction="http://tempuri.org/IProducto/ListarProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Producto>> ListarProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/ModificarProducto", ReplyAction="http://tempuri.org/IProducto/ModificarProductoResponse")]
        Entidades.Producto ModificarProducto(Entidades.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/ModificarProducto", ReplyAction="http://tempuri.org/IProducto/ModificarProductoResponse")]
        System.Threading.Tasks.Task<Entidades.Producto> ModificarProductoAsync(Entidades.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/EliminarProducto", ReplyAction="http://tempuri.org/IProducto/EliminarProductoResponse")]
        Entidades.Producto EliminarProducto(Entidades.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/EliminarProducto", ReplyAction="http://tempuri.org/IProducto/EliminarProductoResponse")]
        System.Threading.Tasks.Task<Entidades.Producto> EliminarProductoAsync(Entidades.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamiliasProdcuto/InsertarFamilia", ReplyAction="http://tempuri.org/IFamiliasProdcuto/InsertarFamiliaResponse")]
        Entidades.Cat_Familias_Productos InsertarFamilia(Entidades.Cat_Familias_Productos familiaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamiliasProdcuto/InsertarFamilia", ReplyAction="http://tempuri.org/IFamiliasProdcuto/InsertarFamiliaResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Familias_Productos> InsertarFamiliaAsync(Entidades.Cat_Familias_Productos familiaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamiliasProdcuto/ListarFamilia", ReplyAction="http://tempuri.org/IFamiliasProdcuto/ListarFamiliaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Familias_Productos> ListarFamilia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamiliasProdcuto/ListarFamilia", ReplyAction="http://tempuri.org/IFamiliasProdcuto/ListarFamiliaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Familias_Productos>> ListarFamiliaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamiliasProdcuto/ModificarFamilia", ReplyAction="http://tempuri.org/IFamiliasProdcuto/ModificarFamiliaResponse")]
        Entidades.Cat_Familias_Productos ModificarFamilia(Entidades.Cat_Familias_Productos familiaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamiliasProdcuto/ModificarFamilia", ReplyAction="http://tempuri.org/IFamiliasProdcuto/ModificarFamiliaResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Familias_Productos> ModificarFamiliaAsync(Entidades.Cat_Familias_Productos familiaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamiliasProdcuto/BorrarFamilia", ReplyAction="http://tempuri.org/IFamiliasProdcuto/BorrarFamiliaResponse")]
        Entidades.Cat_Familias_Productos BorrarFamilia(Entidades.Cat_Familias_Productos familiaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamiliasProdcuto/BorrarFamilia", ReplyAction="http://tempuri.org/IFamiliasProdcuto/BorrarFamiliaResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Familias_Productos> BorrarFamiliaAsync(Entidades.Cat_Familias_Productos familiaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGruposProducto/InsertarGrupo", ReplyAction="http://tempuri.org/IGruposProducto/InsertarGrupoResponse")]
        Entidades.Cat_Grupos_Productos InsertarGrupo(Entidades.Cat_Grupos_Productos grupoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGruposProducto/InsertarGrupo", ReplyAction="http://tempuri.org/IGruposProducto/InsertarGrupoResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Grupos_Productos> InsertarGrupoAsync(Entidades.Cat_Grupos_Productos grupoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGruposProducto/ListarGrupo", ReplyAction="http://tempuri.org/IGruposProducto/ListarGrupoResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Grupos_Productos> ListarGrupo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGruposProducto/ListarGrupo", ReplyAction="http://tempuri.org/IGruposProducto/ListarGrupoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Grupos_Productos>> ListarGrupoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGruposProducto/ModificarGrupo", ReplyAction="http://tempuri.org/IGruposProducto/ModificarGrupoResponse")]
        Entidades.Cat_Grupos_Productos ModificarGrupo(Entidades.Cat_Grupos_Productos grupoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGruposProducto/ModificarGrupo", ReplyAction="http://tempuri.org/IGruposProducto/ModificarGrupoResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Grupos_Productos> ModificarGrupoAsync(Entidades.Cat_Grupos_Productos grupoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGruposProducto/EliminarGrupo", ReplyAction="http://tempuri.org/IGruposProducto/EliminarGrupoResponse")]
        Entidades.Cat_Grupos_Productos EliminarGrupo(Entidades.Cat_Grupos_Productos grupoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGruposProducto/EliminarGrupo", ReplyAction="http://tempuri.org/IGruposProducto/EliminarGrupoResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Grupos_Productos> EliminarGrupoAsync(Entidades.Cat_Grupos_Productos grupoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasProducto/InsertarMarca", ReplyAction="http://tempuri.org/IMarcasProducto/InsertarMarcaResponse")]
        Entidades.Cat_Marcas_Prodcutos InsertarMarca(Entidades.Cat_Marcas_Prodcutos marcaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasProducto/InsertarMarca", ReplyAction="http://tempuri.org/IMarcasProducto/InsertarMarcaResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Marcas_Prodcutos> InsertarMarcaAsync(Entidades.Cat_Marcas_Prodcutos marcaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasProducto/ListarMarca", ReplyAction="http://tempuri.org/IMarcasProducto/ListarMarcaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Marcas_Prodcutos> ListarMarca();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasProducto/ListarMarca", ReplyAction="http://tempuri.org/IMarcasProducto/ListarMarcaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Marcas_Prodcutos>> ListarMarcaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasProducto/ModificarMarca", ReplyAction="http://tempuri.org/IMarcasProducto/ModificarMarcaResponse")]
        Entidades.Cat_Marcas_Prodcutos ModificarMarca(Entidades.Cat_Marcas_Prodcutos marcaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasProducto/ModificarMarca", ReplyAction="http://tempuri.org/IMarcasProducto/ModificarMarcaResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Marcas_Prodcutos> ModificarMarcaAsync(Entidades.Cat_Marcas_Prodcutos marcaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasProducto/EliminarMarca", ReplyAction="http://tempuri.org/IMarcasProducto/EliminarMarcaResponse")]
        Entidades.Cat_Marcas_Prodcutos EliminarMarca(Entidades.Cat_Marcas_Prodcutos marcaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasProducto/EliminarMarca", ReplyAction="http://tempuri.org/IMarcasProducto/EliminarMarcaResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Marcas_Prodcutos> EliminarMarcaAsync(Entidades.Cat_Marcas_Prodcutos marcaProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotas/InsertarNota", ReplyAction="http://tempuri.org/INotas/InsertarNotaResponse")]
        Entidades.Nota InsertarNota(Entidades.Nota nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotas/InsertarNota", ReplyAction="http://tempuri.org/INotas/InsertarNotaResponse")]
        System.Threading.Tasks.Task<Entidades.Nota> InsertarNotaAsync(Entidades.Nota nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotas/ListarNota", ReplyAction="http://tempuri.org/INotas/ListarNotaResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Nota> ListarNota();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotas/ListarNota", ReplyAction="http://tempuri.org/INotas/ListarNotaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Nota>> ListarNotaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotas/ModificarNota", ReplyAction="http://tempuri.org/INotas/ModificarNotaResponse")]
        Entidades.Nota ModificarNota(Entidades.Nota nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotas/ModificarNota", ReplyAction="http://tempuri.org/INotas/ModificarNotaResponse")]
        System.Threading.Tasks.Task<Entidades.Nota> ModificarNotaAsync(Entidades.Nota nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotas/EliminarNota", ReplyAction="http://tempuri.org/INotas/EliminarNotaResponse")]
        Entidades.Nota EliminarNota(Entidades.Nota nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotas/EliminarNota", ReplyAction="http://tempuri.org/INotas/EliminarNotaResponse")]
        System.Threading.Tasks.Task<Entidades.Nota> EliminarNotaAsync(Entidades.Nota nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciosProducto/InsertarPrecio", ReplyAction="http://tempuri.org/IPreciosProducto/InsertarPrecioResponse")]
        Entidades.Precios_Prodcutos InsertarPrecio(Entidades.Precios_Prodcutos precioProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciosProducto/InsertarPrecio", ReplyAction="http://tempuri.org/IPreciosProducto/InsertarPrecioResponse")]
        System.Threading.Tasks.Task<Entidades.Precios_Prodcutos> InsertarPrecioAsync(Entidades.Precios_Prodcutos precioProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciosProducto/ListarPrecio", ReplyAction="http://tempuri.org/IPreciosProducto/ListarPrecioResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Precios_Prodcutos> ListarPrecio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciosProducto/ListarPrecio", ReplyAction="http://tempuri.org/IPreciosProducto/ListarPrecioResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Precios_Prodcutos>> ListarPrecioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciosProducto/ModificarPrecio", ReplyAction="http://tempuri.org/IPreciosProducto/ModificarPrecioResponse")]
        Entidades.Precios_Prodcutos ModificarPrecio(Entidades.Precios_Prodcutos precioProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciosProducto/ModificarPrecio", ReplyAction="http://tempuri.org/IPreciosProducto/ModificarPrecioResponse")]
        System.Threading.Tasks.Task<Entidades.Precios_Prodcutos> ModificarPrecioAsync(Entidades.Precios_Prodcutos precioProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciosProducto/EliminarPrecio", ReplyAction="http://tempuri.org/IPreciosProducto/EliminarPrecioResponse")]
        Entidades.Precios_Prodcutos EliminarPrecio(Entidades.Precios_Prodcutos precioProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciosProducto/EliminarPrecio", ReplyAction="http://tempuri.org/IPreciosProducto/EliminarPrecioResponse")]
        System.Threading.Tasks.Task<Entidades.Precios_Prodcutos> EliminarPrecioAsync(Entidades.Precios_Prodcutos precioProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/InsertarProveedor", ReplyAction="http://tempuri.org/IProveedores/InsertarProveedorResponse")]
        Entidades.Cat_Provedores InsertarProveedor(Entidades.Cat_Provedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/InsertarProveedor", ReplyAction="http://tempuri.org/IProveedores/InsertarProveedorResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Provedores> InsertarProveedorAsync(Entidades.Cat_Provedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ListarProveedor", ReplyAction="http://tempuri.org/IProveedores/ListarProveedorResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Provedores> ListarProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ListarProveedor", ReplyAction="http://tempuri.org/IProveedores/ListarProveedorResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Provedores>> ListarProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ModificarProveedor", ReplyAction="http://tempuri.org/IProveedores/ModificarProveedorResponse")]
        Entidades.Cat_Provedores ModificarProveedor(Entidades.Cat_Provedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ModificarProveedor", ReplyAction="http://tempuri.org/IProveedores/ModificarProveedorResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Provedores> ModificarProveedorAsync(Entidades.Cat_Provedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/EliminarProveedor", ReplyAction="http://tempuri.org/IProveedores/EliminarProveedorResponse")]
        Entidades.Cat_Provedores EliminarProveedor(Entidades.Cat_Provedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/EliminarProveedor", ReplyAction="http://tempuri.org/IProveedores/EliminarProveedorResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Provedores> EliminarProveedorAsync(Entidades.Cat_Provedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiposProducto/InsertarTipo", ReplyAction="http://tempuri.org/ITiposProducto/InsertarTipoResponse")]
        Entidades.Cat_Tipos_Prodcutos InsertarTipo(Entidades.Cat_Tipos_Prodcutos tipoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiposProducto/InsertarTipo", ReplyAction="http://tempuri.org/ITiposProducto/InsertarTipoResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Tipos_Prodcutos> InsertarTipoAsync(Entidades.Cat_Tipos_Prodcutos tipoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiposProducto/ListarTipo", ReplyAction="http://tempuri.org/ITiposProducto/ListarTipoResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Tipos_Prodcutos> ListarTipo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiposProducto/ListarTipo", ReplyAction="http://tempuri.org/ITiposProducto/ListarTipoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Tipos_Prodcutos>> ListarTipoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiposProducto/ModificarTipo", ReplyAction="http://tempuri.org/ITiposProducto/ModificarTipoResponse")]
        Entidades.Cat_Tipos_Prodcutos ModificarTipo(Entidades.Cat_Tipos_Prodcutos tipoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiposProducto/ModificarTipo", ReplyAction="http://tempuri.org/ITiposProducto/ModificarTipoResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Tipos_Prodcutos> ModificarTipoAsync(Entidades.Cat_Tipos_Prodcutos tipoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiposProducto/EliminarTipo", ReplyAction="http://tempuri.org/ITiposProducto/EliminarTipoResponse")]
        Entidades.Cat_Tipos_Prodcutos EliminarTipo(Entidades.Cat_Tipos_Prodcutos tipoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiposProducto/EliminarTipo", ReplyAction="http://tempuri.org/ITiposProducto/EliminarTipoResponse")]
        System.Threading.Tasks.Task<Entidades.Cat_Tipos_Prodcutos> EliminarTipoAsync(Entidades.Cat_Tipos_Prodcutos tipoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadesPaquetes/InsertarUnidadPaquete", ReplyAction="http://tempuri.org/IUnidadesPaquetes/InsertarUnidadPaqueteResponse")]
        Entidades.Productos_Unidades_Paquetes InsertarUnidadPaquete(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadesPaquetes/InsertarUnidadPaquete", ReplyAction="http://tempuri.org/IUnidadesPaquetes/InsertarUnidadPaqueteResponse")]
        System.Threading.Tasks.Task<Entidades.Productos_Unidades_Paquetes> InsertarUnidadPaqueteAsync(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadesPaquetes/ListarUnidadPaquete", ReplyAction="http://tempuri.org/IUnidadesPaquetes/ListarUnidadPaqueteResponse")]
        System.Collections.ObjectModel.ObservableCollection<Entidades.Productos_Unidades_Paquetes> ListarUnidadPaquete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadesPaquetes/ListarUnidadPaquete", ReplyAction="http://tempuri.org/IUnidadesPaquetes/ListarUnidadPaqueteResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Productos_Unidades_Paquetes>> ListarUnidadPaqueteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadesPaquetes/ModificarUnidadPaquete", ReplyAction="http://tempuri.org/IUnidadesPaquetes/ModificarUnidadPaqueteResponse")]
        Entidades.Productos_Unidades_Paquetes ModificarUnidadPaquete(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadesPaquetes/ModificarUnidadPaquete", ReplyAction="http://tempuri.org/IUnidadesPaquetes/ModificarUnidadPaqueteResponse")]
        System.Threading.Tasks.Task<Entidades.Productos_Unidades_Paquetes> ModificarUnidadPaqueteAsync(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadesPaquetes/EliminarUnidadPaquete", ReplyAction="http://tempuri.org/IUnidadesPaquetes/EliminarUnidadPaqueteResponse")]
        Entidades.Productos_Unidades_Paquetes EliminarUnidadPaquete(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadesPaquetes/EliminarUnidadPaquete", ReplyAction="http://tempuri.org/IUnidadesPaquetes/EliminarUnidadPaqueteResponse")]
        System.Threading.Tasks.Task<Entidades.Productos_Unidades_Paquetes> EliminarUnidadPaqueteAsync(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILaPapeChannel : LaPapeConsola.ServicioLaPape.ILaPape, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LaPapeClient : System.ServiceModel.ClientBase<LaPapeConsola.ServicioLaPape.ILaPape>, LaPapeConsola.ServicioLaPape.ILaPape {
        
        public LaPapeClient() {
        }
        
        public LaPapeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LaPapeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LaPapeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LaPapeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.Producto InsertarProducto(Entidades.Producto producto) {
            return base.Channel.InsertarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Producto> InsertarProductoAsync(Entidades.Producto producto) {
            return base.Channel.InsertarProductoAsync(producto);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Producto> ListarProducto() {
            return base.Channel.ListarProducto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Producto>> ListarProductoAsync() {
            return base.Channel.ListarProductoAsync();
        }
        
        public Entidades.Producto ModificarProducto(Entidades.Producto producto) {
            return base.Channel.ModificarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Producto> ModificarProductoAsync(Entidades.Producto producto) {
            return base.Channel.ModificarProductoAsync(producto);
        }
        
        public Entidades.Producto EliminarProducto(Entidades.Producto producto) {
            return base.Channel.EliminarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Producto> EliminarProductoAsync(Entidades.Producto producto) {
            return base.Channel.EliminarProductoAsync(producto);
        }
        
        public Entidades.Cat_Familias_Productos InsertarFamilia(Entidades.Cat_Familias_Productos familiaProducto) {
            return base.Channel.InsertarFamilia(familiaProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Familias_Productos> InsertarFamiliaAsync(Entidades.Cat_Familias_Productos familiaProducto) {
            return base.Channel.InsertarFamiliaAsync(familiaProducto);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Familias_Productos> ListarFamilia() {
            return base.Channel.ListarFamilia();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Familias_Productos>> ListarFamiliaAsync() {
            return base.Channel.ListarFamiliaAsync();
        }
        
        public Entidades.Cat_Familias_Productos ModificarFamilia(Entidades.Cat_Familias_Productos familiaProducto) {
            return base.Channel.ModificarFamilia(familiaProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Familias_Productos> ModificarFamiliaAsync(Entidades.Cat_Familias_Productos familiaProducto) {
            return base.Channel.ModificarFamiliaAsync(familiaProducto);
        }
        
        public Entidades.Cat_Familias_Productos BorrarFamilia(Entidades.Cat_Familias_Productos familiaProducto) {
            return base.Channel.BorrarFamilia(familiaProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Familias_Productos> BorrarFamiliaAsync(Entidades.Cat_Familias_Productos familiaProducto) {
            return base.Channel.BorrarFamiliaAsync(familiaProducto);
        }
        
        public Entidades.Cat_Grupos_Productos InsertarGrupo(Entidades.Cat_Grupos_Productos grupoProducto) {
            return base.Channel.InsertarGrupo(grupoProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Grupos_Productos> InsertarGrupoAsync(Entidades.Cat_Grupos_Productos grupoProducto) {
            return base.Channel.InsertarGrupoAsync(grupoProducto);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Grupos_Productos> ListarGrupo() {
            return base.Channel.ListarGrupo();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Grupos_Productos>> ListarGrupoAsync() {
            return base.Channel.ListarGrupoAsync();
        }
        
        public Entidades.Cat_Grupos_Productos ModificarGrupo(Entidades.Cat_Grupos_Productos grupoProducto) {
            return base.Channel.ModificarGrupo(grupoProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Grupos_Productos> ModificarGrupoAsync(Entidades.Cat_Grupos_Productos grupoProducto) {
            return base.Channel.ModificarGrupoAsync(grupoProducto);
        }
        
        public Entidades.Cat_Grupos_Productos EliminarGrupo(Entidades.Cat_Grupos_Productos grupoProducto) {
            return base.Channel.EliminarGrupo(grupoProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Grupos_Productos> EliminarGrupoAsync(Entidades.Cat_Grupos_Productos grupoProducto) {
            return base.Channel.EliminarGrupoAsync(grupoProducto);
        }
        
        public Entidades.Cat_Marcas_Prodcutos InsertarMarca(Entidades.Cat_Marcas_Prodcutos marcaProducto) {
            return base.Channel.InsertarMarca(marcaProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Marcas_Prodcutos> InsertarMarcaAsync(Entidades.Cat_Marcas_Prodcutos marcaProducto) {
            return base.Channel.InsertarMarcaAsync(marcaProducto);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Marcas_Prodcutos> ListarMarca() {
            return base.Channel.ListarMarca();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Marcas_Prodcutos>> ListarMarcaAsync() {
            return base.Channel.ListarMarcaAsync();
        }
        
        public Entidades.Cat_Marcas_Prodcutos ModificarMarca(Entidades.Cat_Marcas_Prodcutos marcaProducto) {
            return base.Channel.ModificarMarca(marcaProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Marcas_Prodcutos> ModificarMarcaAsync(Entidades.Cat_Marcas_Prodcutos marcaProducto) {
            return base.Channel.ModificarMarcaAsync(marcaProducto);
        }
        
        public Entidades.Cat_Marcas_Prodcutos EliminarMarca(Entidades.Cat_Marcas_Prodcutos marcaProducto) {
            return base.Channel.EliminarMarca(marcaProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Marcas_Prodcutos> EliminarMarcaAsync(Entidades.Cat_Marcas_Prodcutos marcaProducto) {
            return base.Channel.EliminarMarcaAsync(marcaProducto);
        }
        
        public Entidades.Nota InsertarNota(Entidades.Nota nota) {
            return base.Channel.InsertarNota(nota);
        }
        
        public System.Threading.Tasks.Task<Entidades.Nota> InsertarNotaAsync(Entidades.Nota nota) {
            return base.Channel.InsertarNotaAsync(nota);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Nota> ListarNota() {
            return base.Channel.ListarNota();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Nota>> ListarNotaAsync() {
            return base.Channel.ListarNotaAsync();
        }
        
        public Entidades.Nota ModificarNota(Entidades.Nota nota) {
            return base.Channel.ModificarNota(nota);
        }
        
        public System.Threading.Tasks.Task<Entidades.Nota> ModificarNotaAsync(Entidades.Nota nota) {
            return base.Channel.ModificarNotaAsync(nota);
        }
        
        public Entidades.Nota EliminarNota(Entidades.Nota nota) {
            return base.Channel.EliminarNota(nota);
        }
        
        public System.Threading.Tasks.Task<Entidades.Nota> EliminarNotaAsync(Entidades.Nota nota) {
            return base.Channel.EliminarNotaAsync(nota);
        }
        
        public Entidades.Precios_Prodcutos InsertarPrecio(Entidades.Precios_Prodcutos precioProducto) {
            return base.Channel.InsertarPrecio(precioProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Precios_Prodcutos> InsertarPrecioAsync(Entidades.Precios_Prodcutos precioProducto) {
            return base.Channel.InsertarPrecioAsync(precioProducto);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Precios_Prodcutos> ListarPrecio() {
            return base.Channel.ListarPrecio();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Precios_Prodcutos>> ListarPrecioAsync() {
            return base.Channel.ListarPrecioAsync();
        }
        
        public Entidades.Precios_Prodcutos ModificarPrecio(Entidades.Precios_Prodcutos precioProducto) {
            return base.Channel.ModificarPrecio(precioProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Precios_Prodcutos> ModificarPrecioAsync(Entidades.Precios_Prodcutos precioProducto) {
            return base.Channel.ModificarPrecioAsync(precioProducto);
        }
        
        public Entidades.Precios_Prodcutos EliminarPrecio(Entidades.Precios_Prodcutos precioProducto) {
            return base.Channel.EliminarPrecio(precioProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Precios_Prodcutos> EliminarPrecioAsync(Entidades.Precios_Prodcutos precioProducto) {
            return base.Channel.EliminarPrecioAsync(precioProducto);
        }
        
        public Entidades.Cat_Provedores InsertarProveedor(Entidades.Cat_Provedores proveedor) {
            return base.Channel.InsertarProveedor(proveedor);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Provedores> InsertarProveedorAsync(Entidades.Cat_Provedores proveedor) {
            return base.Channel.InsertarProveedorAsync(proveedor);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Provedores> ListarProveedor() {
            return base.Channel.ListarProveedor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Provedores>> ListarProveedorAsync() {
            return base.Channel.ListarProveedorAsync();
        }
        
        public Entidades.Cat_Provedores ModificarProveedor(Entidades.Cat_Provedores proveedor) {
            return base.Channel.ModificarProveedor(proveedor);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Provedores> ModificarProveedorAsync(Entidades.Cat_Provedores proveedor) {
            return base.Channel.ModificarProveedorAsync(proveedor);
        }
        
        public Entidades.Cat_Provedores EliminarProveedor(Entidades.Cat_Provedores proveedor) {
            return base.Channel.EliminarProveedor(proveedor);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Provedores> EliminarProveedorAsync(Entidades.Cat_Provedores proveedor) {
            return base.Channel.EliminarProveedorAsync(proveedor);
        }
        
        public Entidades.Cat_Tipos_Prodcutos InsertarTipo(Entidades.Cat_Tipos_Prodcutos tipoProducto) {
            return base.Channel.InsertarTipo(tipoProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Tipos_Prodcutos> InsertarTipoAsync(Entidades.Cat_Tipos_Prodcutos tipoProducto) {
            return base.Channel.InsertarTipoAsync(tipoProducto);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Tipos_Prodcutos> ListarTipo() {
            return base.Channel.ListarTipo();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Cat_Tipos_Prodcutos>> ListarTipoAsync() {
            return base.Channel.ListarTipoAsync();
        }
        
        public Entidades.Cat_Tipos_Prodcutos ModificarTipo(Entidades.Cat_Tipos_Prodcutos tipoProducto) {
            return base.Channel.ModificarTipo(tipoProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Tipos_Prodcutos> ModificarTipoAsync(Entidades.Cat_Tipos_Prodcutos tipoProducto) {
            return base.Channel.ModificarTipoAsync(tipoProducto);
        }
        
        public Entidades.Cat_Tipos_Prodcutos EliminarTipo(Entidades.Cat_Tipos_Prodcutos tipoProducto) {
            return base.Channel.EliminarTipo(tipoProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cat_Tipos_Prodcutos> EliminarTipoAsync(Entidades.Cat_Tipos_Prodcutos tipoProducto) {
            return base.Channel.EliminarTipoAsync(tipoProducto);
        }
        
        public Entidades.Productos_Unidades_Paquetes InsertarUnidadPaquete(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto) {
            return base.Channel.InsertarUnidadPaquete(unidadPaqueteProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Productos_Unidades_Paquetes> InsertarUnidadPaqueteAsync(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto) {
            return base.Channel.InsertarUnidadPaqueteAsync(unidadPaqueteProducto);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Entidades.Productos_Unidades_Paquetes> ListarUnidadPaquete() {
            return base.Channel.ListarUnidadPaquete();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Entidades.Productos_Unidades_Paquetes>> ListarUnidadPaqueteAsync() {
            return base.Channel.ListarUnidadPaqueteAsync();
        }
        
        public Entidades.Productos_Unidades_Paquetes ModificarUnidadPaquete(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto) {
            return base.Channel.ModificarUnidadPaquete(unidadPaqueteProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Productos_Unidades_Paquetes> ModificarUnidadPaqueteAsync(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto) {
            return base.Channel.ModificarUnidadPaqueteAsync(unidadPaqueteProducto);
        }
        
        public Entidades.Productos_Unidades_Paquetes EliminarUnidadPaquete(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto) {
            return base.Channel.EliminarUnidadPaquete(unidadPaqueteProducto);
        }
        
        public System.Threading.Tasks.Task<Entidades.Productos_Unidades_Paquetes> EliminarUnidadPaqueteAsync(Entidades.Productos_Unidades_Paquetes unidadPaqueteProducto) {
            return base.Channel.EliminarUnidadPaqueteAsync(unidadPaqueteProducto);
        }
    }
}
