//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaPapeEntidades : DbContext
    {
        public LaPapeEntidades()
            : base("name=LaPapeEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Familias_Productos> Cat_Familias_Productos { get; set; }
        public virtual DbSet<Cat_Grupos_Productos> Cat_Grupos_Productos { get; set; }
        public virtual DbSet<Cat_Marcas_Prodcutos> Cat_Marcas_Prodcutos { get; set; }
        public virtual DbSet<Cat_Provedores> Cat_Provedores { get; set; }
        public virtual DbSet<Cat_Tipos_Prodcutos> Cat_Tipos_Prodcutos { get; set; }
        public virtual DbSet<Nota> Notas { get; set; }
        public virtual DbSet<Precios_Prodcutos> Precios_Prodcutos { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Productos_Unidades_Paquetes> Productos_Unidades_Paquetes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
