//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Provedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Provedores()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public int Id_Proveedor { get; set; }
        public string Nombre_Proveedor { get; set; }
        public string Direccion_1_Proveedor { get; set; }
        public string Direccion_2_Proveedor { get; set; }
        public string Direccion_3_Proveedor { get; set; }
        public string Telefono_1_Provedor { get; set; }
        public string Telefono_2_Provedor { get; set; }
        public string Telefono_3_Provedor { get; set; }
        public Nullable<int> Id_Nota { get; set; }
    
        public virtual Nota Nota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
