//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precios_Prodcutos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Precios_Prodcutos()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public int Id_Precios_Producto { get; set; }
        public decimal Costo_Mes_Actual { get; set; }
        public decimal Costo_Mes_Anterior { get; set; }
        public decimal Costo_Unitario { get; set; }
        public decimal Costo_Paqeute { get; set; }
        public decimal Min_Precio_Unidad_Publico { get; set; }
        public decimal Precio_Unidad_Publico { get; set; }
        public int Porciento_Aplicado { get; set; }
        public decimal Min_Precio_Paquete_Publico { get; set; }
        public decimal Precio_Paquete_Publico { get; set; }
        public Nullable<int> Id_Nota { get; set; }
    
        public virtual Nota Nota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
