//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string SKU { get; set; }
        public int Id_Producto { get; set; }
        public int Id_Tipo_Producto { get; set; }
        public byte[] Descripcion_Producto { get; set; }
        public string Tamaño_Producto { get; set; }
        public string Contenido_Prodcuto { get; set; }
        public int Id_Grupo_Producto { get; set; }
        public int Id_Familia_Producto { get; set; }
        public int Id_Marca_Prodcuto { get; set; }
        public int Id_Precios_Producto { get; set; }
        public int Id_Proveedor { get; set; }
        public int Id_Unidades_Paquetes { get; set; }
        public Nullable<int> Id_Nota { get; set; }
    
        public virtual Cat_Familias_Productos Cat_Familias_Productos { get; set; }
        public virtual Cat_Grupos_Productos Cat_Grupos_Productos { get; set; }
        public virtual Cat_Marcas_Prodcutos Cat_Marcas_Prodcutos { get; set; }
        public virtual Cat_Provedores Cat_Provedores { get; set; }
        public virtual Cat_Tipos_Prodcutos Cat_Tipos_Prodcutos { get; set; }
        public virtual Nota Nota { get; set; }
        public virtual Precios_Prodcutos Precios_Prodcutos { get; set; }
        public virtual Productos_Unidades_Paquetes Productos_Unidades_Paquetes { get; set; }
    }
}
